### ISSUE TITLE
compile error on aarch64

### ISSUE THREAD

**Issue by arjunskumar** [ivipsourcecode/dxslam#18]
any solution to compile on aarch64?

**Comment by arjunskumar** [comment]
Able to compile with [https://github.com/OpenVSLAM-Community/FBoW/issues/2](https://github.com/OpenVSLAM-Community/FBoW/issues/2)

**Comment by MRRH-Codes** [comment]
Hi, how do you compiled it on the jetson?

**Comment by AusbelDev** [comment]
Hi @arjunskumar how do you compiled dxslam on the jetson?

**Comment by arjunskumar** [comment]
@MRRH-Codes Compile with the develop branch of [FBoW](https://github.com/OpenVSLAM-Community/FBoW/tree/develop)

**Comment by AusbelDev** [comment]
@arjunskumar i already did it but now i have new errors, can't compile dxslam. Im trying to compile it in a jetson AGX Xavier. Can you help me?

**Comment by arjunskumar** [comment]
@MRRH-Codes can you show the error please
