### ISSUE TITLE
terminate called after throwing an instance of 'std::runtime_error'

### ISSUE THREAD

**Issue by zainmehdi** [ivipsourcecode/dxslam#5]
I am trying to run dxslam. There were few files missing like ORBvoc.txt so I got it from ORBSLAM folder. Then TUM1.yaml file was also missing which I also copied from ORB folder. After running RGBD example I get the following error.

`Loading ORB Vocabulary. This could take a while...
terminate called after throwing an instance of 'std::runtime_error'
  what():  Vocabulary::fromStream invalid signature
Aborted (core dumped)
`

**Comment by CSU-NXY** [comment]
Try use DXSLAM.fbow instead of ORBvoc.txt

**Comment by zainmehdi** [comment]
Yes it works. Thanks
