### ISSUE TITLE
Possible license violation

### ISSUE THREAD

**Issue by lajoiepy** [ivipsourcecode/dxslam#7]
Hi! I want to inform you that copying ORB-SLAM2 code and removing the heading (such as in https://github.com/ivipsourcecode/dxslam/blob/master/src/Map.cc) is unethical and in possible violation of their license. You should do a proper fork of their repo.
@raulmur

**Comment by cedrusx** [comment]
Thank you very much @lajoiepy for the reminder.
@OldAAAA would you take care of this? At least we should retain ORB-SLAM2's license file and the copyright headings in each source file. Please give an update here when you've done with that.

**Comment by ivipsourcecode** [comment]
> Hi! I want to inform you that copying ORB-SLAM2 code and removing the heading (such as in https://github.com/ivipsourcecode/dxslam/blob/master/src/Map.cc) is unethical and in possible violation of their license. You should do a proper fork of their repo.
> @raulmur

Thank you! we've solved that problem.
